[tool.poetry]
name = "microscope-metrics-omero"
version = "0.1.0"
description = ""
authors = ["Julio Mateos Langerak <julio.mateos-langerak@igh.cnrs.fr>"]
readme = "README.md"
packages = [{include = "microscope_metrics_omero"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

